### ISSUE TITLE
Use the `codec` struct tag, instead of `json`.

### ISSUE THREAD

**Issue by jmalloc** [rinq/rinq-go#111]
http://ugorji.net/blog/go-codec-primer#drop-in-replacement-for-encoding-json-json-key-in-struct-tag-supported

**Comment by jmalloc** [comment]
@koshatul what was the reason you said that this didn't work for your stuff?

**Comment by koshatul** [comment]
I can't remember, I think only to indicate it was go-codec instead of just encoding/json.

I think I ended up using `json` anyway because of the couchdb library I shared some structs with.
