### ISSUE TITLE
Implement method for "clearing" all attributes in a specific namespace.

### ISSUE THREAD

**Issue by jmalloc** [rinq/rinq-go#132]
This is a session operation that sets all attributes in a given namespace to the empty string. This is an "update-like" operation insofar as revision-based optimistic locking must be applied as it is for `Update()` or `Destroy()`.

We will have to make a decision about how to handle frozen attributes, some options are:

- (a) always fail if any attribute is frozen
- (b) ignore frozen attributes altogether
- (c) allow the user to specify the behaviour

My inclination is quite strongly towards (a), as it honours the existing semantics of `Update()`.

/cc @ezzatron

**Comment by jmalloc** [comment]
Perhaps `Revision.Clear(ctx, ns)` as far as a method name.

**Comment by ezzatron** [comment]
If you go with (a) I can't see this being used a lot. The use case we had in mind was clearing authentication data for long-running websocket connections, which is a case where we'd probably always want to use frozen attributes for (at least) IP addresses.

It would be nice not to be forced into a trade-off.

**Comment by jmalloc** [comment]
In that particular case I would expect those IP addresses to be in a different namespace (`rinq.httpd`), as they are not auth related.

**Comment by ezzatron** [comment]
Yeah, I guess that works.
