### ISSUE TITLE
Use `repr.Escape()` for all attribute string representations.

### ISSUE THREAD

**Issue by jmalloc** [rinq/rinq-go#151]
`repr.Escape()` is a function that formats strings to be readable for log output, it "escapes" them (using JSON notation) only if they contain characters such as spaces, quotes, etc. The idea being you can get a short string representation that's easy to read for the common case, such as `user_id`.

`repr.Escape()` is currently used to build string representations of `constraint.Constraint` values, but needs to be used anywhere an attribute is stringified.  I *think* after the recent spate of refactoring, that `rinq.Attr` might be the only remaining place where this is necessary.

**Comment by jmalloc** [comment]
Also open to new names for this function, `Escape()` isn't quite right.

**Comment by koden-km** [comment]
I'm not sure about any better names. The only thing I can think of is `Stringify()`, but they are already strings. What name did you use when you had the `repr` python and/or php library?

**Comment by jmalloc** [comment]
There was no equivalent in `repr`. No problems, we can leave it as `Escape` for now.
