### ISSUE TITLE
Add `Session.CallAsync`

### ISSUE THREAD

**Issue by jmalloc** [rinq/rinq-go#21]
FYI @ezzatron

`CallAsync` is a non-blocking variant of `Call`. Unlike `Execute`, it still expects a response from the server, but the response is delivered to a "command response handler" which is configured on a per-session basis, much like a notification handler. The command response handler is passed the namespace, command, payload and error.

TL;DR `CallAsync` is a variant of `Call` where the application is responsible for request/response correlation.

**Comment by jmalloc** [comment]
@ezzatron can you have a glance at 0dd6d1993f6f8d5a9d7fc6ef03bdc1d011db6495 and tell me if it all sounds in line with your expectations.

**Comment by ezzatron** [comment]
Looks right to me.
